plugins {
     id 'org.jetbrains.kotlin.jvm'        version '2.4.10'
     id 'org.jetbrains.intellij.platform' version '2.18.1'
}

buildDir = 'gradle-build'
version = ext.PluginVersion

sourceSets {
    main {
        java.srcDir      'src/rider/main/kotlin'
        resources.srcDir 'src/rider/main/resources'
    }
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
        jetbrainsRuntime()
    }
}

dependencies {
    intellijPlatform {
        rider(ProductVersion) {
            useInstaller = false
        }
        jetbrainsRuntime()
        bundledModule("intellij.rider.rdclient.dotnet")
    }
}

intellijPlatform {
    pluginConfiguration {
        name = rootProject.name
    }
}

prepareSandbox {
    def dotNetFiles = [
        "${DotNetOutputDirectory}/${DotNetProjectName}.dll",
        "${DotNetOutputDirectory}/${DotNetProjectName}.pdb",
    ]

    dotNetFiles.forEach { f ->
        def file = file(f)
        from(file) {
            into "${rootProject.name}/dotnet"
        }
    }

    doLast {
        dotNetFiles.forEach { f ->
            if (!file(f).exists()) {
                throw new RuntimeException("File $f does not exist")
            }
        }
    }
}

runIde {
    if (project.hasProperty('RunIdeSolution')) {
        argumentProviders.add({ [project.property('RunIdeSolution').toString()] } as CommandLineArgumentProvider)
    }
}

wrapper {
    gradleVersion    = '9.7.1'
    distributionType = Wrapper.DistributionType.ALL
    distributionUrl  = "https://cache-redirector.jetbrains.com/services.gradle.org/distributions/gradle-${gradleVersion}-all.zip"
}
