# Any property can be overwritten from command-line via
#   -P<propertyName>=<value>

PluginVersion=_PLACEHOLDER_
ProductVersion=_PLACEHOLDER_
# Marketplace release channel; 'default' is the stable one
PluginChannel=default
DotNetOutputDirectory=./src/ReSharper.Structured.Logging/bin/ReSharper.Structured.Logging.Rider/Debug
DotNetProjectName=ReSharper.Structured.Logging.Rider

# Disable the Gradle daemon so CI processes exit cleanly after the build
org.gradle.daemon=false

# We need it to avoid bundle Kotlin jars into plugin
kotlin.stdlib.default.dependency=false
